blank_issues_enabled: false
issue_templates:
  - name: "ğŸ ë²„ê·¸ ë¦¬í¬íŠ¸"
    description: "ë²„ê·¸ë¥¼ ì‹ ê³ í•  ë•Œ ì‚¬ìš©í•˜ëŠ” í…œí”Œë¦¿ì…ë‹ˆë‹¤."
    title: "[Bug] "
    labels: ["bug"]
    assignees: []
    body: .github/ISSUE_TEMPLATE/ì½”ë“œ-í”Œë˜ë‹›-ë²„ê·¸ë¦¬í¬íŠ¸-êµ¬ì¡°.md
